version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test_db
      
  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    working_dir: /api/
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src/api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build:
      context: ./src/player-tools-web
      dockerfile: Dockerfile
    working_dir: /web/
    command: sh -c "npm rebuild esbuild && npm run host"
    volumes:
      - ./src/player-tools-web:/web
    ports:
      - "5173:5173"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
